# .NET Technology Configuration
# Used by composite workflows (build.yml, test.yml) to execute .NET-specific commands

name: dotnet
default_version: "8.0"

# SDK Setup
setup_action: actions/setup-dotnet@v4
setup_with:
  dotnet-version: ${{ inputs.technology_version || '8.0' }}

# Cache Configuration
cache:
  path: ~/.nuget/packages
  key_pattern: "${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}"
  restore_keys: |
    ${{ runner.os }}-nuget-

# Build/Test Commands
commands:
  restore: dotnet restore
  build: dotnet build --no-restore --configuration Release
  test: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx"
  publish: dotnet publish --no-restore --configuration Release --output ./publish

# File Patterns (for discovery)
file_patterns:
  project: "**/*.csproj"
  solution: "**/*.sln"
  test_project: "**/*Tests.csproj"

# Build Arguments (passed to docker build)
docker_build_args:
  - name: PROJECT_NAME
    description: "Name of the .NET project to build"
    required: true
