# Node.js Technology Configuration
# Used by composite workflows (build.yml, test.yml) to execute Node.js-specific commands

name: node
default_version: "20"

# SDK Setup
setup_action: actions/setup-node@v4
setup_with:
  node-version: ${{ inputs.technology_version || '20' }}
  cache: 'npm'

# Cache Configuration
cache:
  path: ~/.npm
  key_pattern: "${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}"
  restore_keys: |
    ${{ runner.os }}-node-

# Build/Test Commands
commands:
  restore: npm ci
  build: npm run build
  test: npm test
  lint: npm run lint

# File Patterns (for discovery)
file_patterns:
  project: "**/package.json"
  lock_file: "**/package-lock.json"
  test_config: "**/jest.config.*"

# Build Arguments (passed to docker build)
docker_build_args:
  - name: NODE_ENV
    description: "Node environment (production/development)"
    default: "production"
